.\"     Title: KWBACKUPRC
.\"    Author: Kai Wilke <kiste@netzworkk.de>
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 06/13/2008
.\"    Manual: 
.\"    Source: Version 0.1.5
.\"
.TH "KWBACKUPRC" "5" "06/13/2008" "Version 0.1.5" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
kwbackuprc \- Konfigurations Datei f\(:ur kwbackup.
.SH "BESCHREIBUNG"
.PP
Beim Start von
\fBkwbackup\fR
wird die Datei
\fI~/\&.kwtools/kwbackuprc\fR
eingelesen\&. Sie beinhaltet die Variablen die von
\fBkwbackup\fR
ben\(:otigt werden\&. Beginnt eine Zeile mit
\(lq#\(rq
oder ist leer wird dies als Kommentar interpretiert\&. Sie sollten diese Datei mit
\fBkwbackup\fR
bearbeiten\&.
.SH "OPTIONEN"
.PP
\fBBACKUP_PATH\fR
.RS 4
Geben Sie hier das Backupverzeichnis an\&. Aus BACKUP_PATH wird BACKUP_PATH/HOSTNAME/{sys,dirs}\&.
.RE
.PP
\fBMOUNT_PATH\fR
.RS 4
Geben Sie hier das Verzeichnis an, welches gemountet werden muss\&. Es muss in der Datei
\fI/etc/fstab\fR
stehen\&.
.RE
.PP
\fBDIRS\fR
.RS 4
Verzeichnisse die regelm\(:assig gesichert werden sollen, getrennt durch ein Leerzeichen (\fI/home /mnt/audio\fR)\&. Nicht das Rootfilesystem (\fI/\fR), das wird auch so gesichert\&.
.RE
.SH "DATEI"
.PP
\fI~/\&.kwtools/kwbackuprc\fR
.RS 4
Dies ist die Konfigurations Datei f\(:ur
\fBkwbackup\fR\&. F\(:ur weitere Details siehe
\fBkwbackup\fR(1)\&.
.RE
.SH "SIEHE AUCH"
.PP
\fBkwbackup\fR(1),
\fBtar\fR(1)
.SH "AUTOR"
.PP
\fBKai Wilke\fR <\&kiste@netzworkk\&.de\&>
.sp -1n
.IP "" 4
Die Manpage wurde in DocBook XML f\(:ur die Debian Distribution geschrieben\&.
.SH "COPYRIGHT"
Copyright \(co 2002-2008 Kai Wilke
.br
