.\"     Title: KWFILM2FILMRC
.\"    Author: Kai Wilke <kiste@netzworkk.de>
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 06/14/2008
.\"    Manual: 
.\"    Source: Version 0.0.2
.\"
.TH "KWFILM2FILMRC" "5" "06/14/2008" "Version 0.0.2" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
kwfilm2filmrc \- Konfigurations Datei f\(:ur kwvmstat.
.SH "BESCHREIBUNG"
.PP
Beim Start von
\fBkwfilm2film\fR
wird die Datei
\fI~/\&.kwtools/kwfilm2filmrc\fR
eingelesen\&. Diese beinhaltet die Variablen die von
\fBmplex\fR
und
\fBtranscode\fR
zum konvertieren von Videos ben\(:otigt werden\&. Beginnt eine Zeile mit
\(lq#\(rq
oder ist leer wird dies als Kommentar interpretiert\&.
.SH "OPTIONEN"
.PP
\fBBITR\fR
.RS 4
Geben Sie hier die Audio Encoder Bitrate an, von
\fB8\fR
\-
\fB320 Bit\fR\&. Diese muss ein vielfaches von
\fI8\fR
sein (\fB8\fR,
\fB16\fR,
\fB24\fR, \&.\&.\&.)\&.
.RE
.PP
\fBAUDIO_EXPORT_MODUL\fR
.RS 4
Geben Sie hier das Audio Export Modul an\&.
.RE
.PP
\fBAUDIO_IMPORT_MODUL\fR
.RS 4
Geben Sie hier das Audio Import Modul an\&.
.RE
.PP
\fBTV_FORMAT\fR
.RS 4
Geben Sie hier die Fernseher Aufl\(:osung an\&. In Europa ist das Format
\fIPAL\fR
Standard\&. Dies kann eine der folgenden sein:
\fB352X240\fR
\fINTSC/DVD\fR,
\fB352X240\fR
\fINTSC/VCD\fR,
\fB352x288\fR
\fIPAL/DVD\fR,
\fB352x288\fR
\fIPAL/VCD\fR,
\fB352x480\fR
\fINTSC/DVD\fR,
\fB352x576\fR
\fIPAL/DVD\fR,
\fB480x480\fR
\fINTSC/(S)VCD\fR,
\fB480x576\fR
\fIPAL/(S)VCD\fR,
\fB704x480\fR
\fINTSC/DVD\fR,
\fB704x576\fR
\fIPAL/DVD\fR,
\fB720x480\fR
\fINTSC/DVD\fR,
\fB720x576\fR
\fIPAL/DVD\fR\&.
.RE
.PP
\fBBUFFER_SIZE\fR
.RS 4
Geben Sie hier die Buffer Gr\(:osse, f\(:ur Ihren Film an (\fB46\-9192\fR)\&. Alle Werte sind in Kilobytes\&.
\fB46\fR
ist sehr klein und kann f\(:ur
\(lq\fBvcd\fR\(rq
benutzt werden, w\(:ahrend
\(lq\fBsvcd\fR\(rq
mehr als
\fB230 KByte\fR
haben sollte\&.
.RE
.PP
\fBSAMPLE\fR
.RS 4
Geben Sie hier die Audio Sample Rate ein\&.
\fB22050\fR
ist Mono und
\fB44100\fR
ist Stereo\&.
.RE
.PP
\fBVIDEO_EXPORT_MODUL\fR
.RS 4
Geben Sie hier das Video Export Modul an\&.
.RE
.PP
\fBVIDEO_IMPORT_MODUL\fR
.RS 4
Geben Sie hier das Video Import Modul an\&.
.RE
.PP
\fBSPLIT_SIZE\fR
.RS 4
Geben Sie hier die Datei Gr\(:osse an, ab der gesplittet werden soll\&. Bedenken Sie das ihr Kernel diese Gr\(:osse unterst\(:utzen muss (\fBCONFIG_HIGHMEM*\fR)\&. Zur Auswahl stehen,
\fB650\fR,
\fB680\fR,
\fB700\fR,
\fB800\fR,
\fB1000\fR,
\fB2000\fR,
\fB4000\fR
und
\fB64000 Mb\fR\&.
.RE
.PP
\fBFILM_PATH\fR
.RS 4
Geben Sie hier das Verzeichnis an in dem standardm\(:assig Ihre Filme liegen\&.
.RE
.PP
\fBMOUNT_PATH\fR
.RS 4
Geben Sie hier das Verzeichnis an, welches eingebunden werden muss, um an Ihre Filme zu kommen\&. Dieses muss in der
\fI/etc/fstab\fR
stehen\&.
.RE
.PP
\fBVIDEO_TYPE\fR
.RS 4
Geben Sie hier den Video Type an in welches der Film konvertiert werden soll\&. Zur Auswahl stehen
\fBdvd\fR,
\fBgeneric_mpeg1\fR,
\fBgeneric_mpeg2\fR,
\fBstill_stream_vcd\fR,
\fBstill_stream_svcd\fR,
\fBsvcd\fR,
\fBuser_rate_vcd\fR,
\fBuser_rate_svcd\fR
oder
\fBvcd\fR
sein\&.
.RE
.SH "DATEI"
.PP
\fI~/\&.kwtools/kwfilm2filmrc\fR
.RS 4
Dies ist die Konfigurations Datei f\(:ur
\fBkwfilm2film\fR
F\(:ur weitere Details siehe
\fBkwfilm2film\fR(1)\&.
.RE
.SH "SIEHE AUCH"
.PP
\fBkwfilm2film\fR(1),
\fBmplex\fR(1),
\fBtranscode\fR(1)
.SH "AUTOR"
.PP
\fBKai Wilke\fR <\&kiste@netzworkk\&.de\&>
.sp -1n
.IP "" 4
Die Manpage wurde in DocBook XML f\(:ur die Debian Distribution geschrieben\&.
.SH "COPYRIGHT"
Copyright \(co 2002-2008 Kai Wilke
.br
