#!/bin/zsh
#
# Autor: Kai Wilke <kiste@netzworkk.de> 27.12.2006
#
# Script: proxy, zum einstellen der Proxy Variablen
# Version: 0.1.20

unsetopt nomatch

trap 'setterm -inversescreen off ; setterm -reset ; rm -rf $SCRIPT_LOCK $gv_WorkDirGlobal >/dev/null 2>&1' EXIT INT

gv_ScriptName=${0##*/}

#
# script_init enthaelt die globalen Scripteinstellungen und laedt
# diese automatisch.
#
autoload script_init

#
# Verzeichniss in denen nach Funktionen gesucht wird
#
if [ -f /usr/local/share/kwtools/functions/var/script_init ] ; then
	PREFIX=/usr/local
else
	PREFIX=/usr
fi
Script_init_Fpath="${PREFIX}/share/kwtools/functions/var"
export TEXTDOMAINDIR="${PREFIX}/share/locale"
export TEXTDOMAIN="$gv_ScriptName"

if [ -z ${(M)${FPATH}##*${Script_init_Fpath}*} ] ; then
	FPATH=$FPATH:${Script_init_Fpath}
fi

# Scriptinitialisierung
script_init
root_check

autoload fhost
# Rechte pruefen
os_check
if_conf_file $OS proxy

#
# Wenn eine /etc/default/proxy Datei vorhanden ist einlesen.
#
if [ -f "$PROXY_FILE" -a "$OS" = Suse ]; then
	source "$PROXY_FILE"
	http_proxy="$HTTP_PROXY"
	ftp_proxy="$FTP_PROXY"
else
	source "$PROXY_FILE"
fi
PROXY_MSG=$(gettext 'Tragen Sie bitte ihren Proxy ein (protokoll://host:port).')
# Funktion haupt_menue{{{
haupt_menue ()
{
	MENU=$(gettext 'http_proxy "$http_proxy" ftp_proxy "$ftp_proxy" speichern "" zurueck ""')
	menubox "$gv_Mainmenu" "$gv_Menupoint" "$MENU"
}
#}}}
#######################################################################
#
# Hauptprogramm
#
#######################################################################
#
haupt_menue
while [ "$gv_Auswahl" ] ; do
	case $gv_Auswahl in
		HELP*)
    	    # Hilfe Messagebox
	        #
			script_help help
			haupt_menue
			;;
		h*)
			# http Proxy einstellen{{{
			#
			inputbox http_proxy "$PROXY_MSG" "$http_proxy"
			if [ "$gv_Auswahl" ] ; then
				case $gv_Auswahl in
					http://*:[1-9][0-9][0-9][0-9])
						Name="${gv_Auswahl%:*}"
						Name1="${Name#*://}"
						fhost "$Name1"
						if [ "$Z_HOST" ] ; then
							http_proxy="$gv_Auswahl"
							unset -- Name Name1
						else
							unset -- Name Name1
						fi
						;;
					*)	no_input_msg
						;;
				esac
			fi
			#}}}
			haupt_menue
			;;
		f*)
			# ftp Proxy einstellen{{{
			#
			inputbox ftp_proxy "$PROXY_MSG" "$ftp_proxy"
			if [ "$gv_Auswahl" ] ; then
				case $gv_Auswahl in
					(http|ftp)://*:[1-9][0-9][0-9][0-9])
						Name="${gv_Auswahl%:*}"
						Name1="${Name#*://}"
						fhost "$Name1"
						if [ "$Z_HOST" ] ; then
							ftp_proxy="$gv_Auswahl"
							unset -- Name Name1
						else
							unset -- Name Name1
						fi
						;;
					*)	no_input_msg
						;;
				esac
			fi
			#}}}
			haupt_menue
			;;
		speichern|save)
			# Konfigiration speichern.{{{
			#
			if [ "$OS" = Suse ] ; then
				> $PROXY_FILE <<< "PROXY_ENABLED=\"yes\"
HTTP_PROXY=\"$http_proxy\"
FTP_PROXY=\"$ftp_proxy\"
NO_PROXY=\"localhost\""
			else
				> $PROXY_FILE <<< "# Beginn $PROXY_FILE
#
# http Proxy (http_proxy=http://rechnername:port)
#
export http_proxy="$http_proxy"

# ftp Proxy (ftp_proxy=http://rechnername:port)
#
export ftp_proxy="$ftp_proxy"
				
# End $PROXY_FILE"
			fi
			break
			#}}}
			;;
		beenden|exit)	break
			;;
	esac
done	
unset -- PROXY_FILE
exit 0
