#!/bin/zsh
#
# Autor: Kai Wilke <kiste@netzworkk.de> 03.06.2011
#
# Script: kwrsync_cron, führt eine syncronisation von Verzeichnissen
#         aus. (cron)
#
# Version: 0.0.6

trap 'rm -rf $gv_WorkDir &>/dev/null' EXIT INT

gv_ScriptName=${0##*/}

# Verzeichniss in denen nach Funktionen gesucht wird
#
if [ -f /usr/local/share/kwtools/functions/sys/script_init ] ; then
	PREFIX=/usr/local
else
	PREFIX=/usr
fi
Script_init_Fpath="${PREFIX}/share/kwtools/functions/sys"
export TEXTDOMAINDIR="${PREFIX}/share/locale"
export TEXTDOMAIN="$gv_ScriptName"

if [ -z ${(M)${FPATH}##*${Script_init_Fpath}*} ] ; then
	FPATH=${Script_init_Fpath}:${FPATH}
fi

Kwrsync_Fpath=${PREFIX}/share/kwtools/functions/kwrsync
if [ -z ${(M)${FPATH}##*${Kwrsync_Fpath}*} ] ; then
	FPATH=${Script_init_Fpath}:${FPATH}
fi

# script_init enthält die globalen Scripteinstellungen und lädt
# diese automatisch.
#
autoload -U script_init

# Scriptinitialisierung
script_init -o

# Wenn eine ~/.kwtools/kwrsyncrc Datei vorhanden ist einlesen.
#
KWRSYNCTAB="${gv_HomePath}/.kwtools/kwrsynctab"
KWRSYNCRC="${gv_HomePath}/.kwtools/kwrsyncrc"
if [ -f "$KWRSYNCRC" ] ; then
	read_file kwrsyncrc
else
	MSG=$(gettext 'Es ist keine Konfigurationsdatei $KWRSYNCRC vorhanden.')
	> ${gv_WorkDir}/kwrsync_cron <<< "$MSG"
	mail -s "kwrsync_cron: kwrsyncrc Error" $USER < ${gv_WorkDir}/kwrsync_cron
	exit 1
fi
# Funktion no_kwrsync_cron_exec# {{{
no_kwrsync_cron_exec() {
	MSG=$(gettext 'Es sind keine Eintrage fuer kwrsync vorhanden.')
	> ${gv_WorkDir}/kwrsync_cron <<< "$MSG"
	mail -s "kwrsync_cron: kwrsynctab Error" $USER < ${gv_WorkDir}/kwrsync_cron
	exit 1
}
## }}}
# Funktion no_kwrsync_cron_home_exec# {{{
no_kwrsync_cron_home_exec() {
	MSG=$(gettext 'Fehler in $KWRSYNCRC.')
	> ${gv_WorkDir}/kwrsync_cron <<< "$MSG"
	mail -s "kwrsync_cron: kwrsyncrc Error" $USER < ${gv_WorkDir}/kwrsync_cron
	exit 1
}
## }}}
#
autoload -U kwrsync_home_exec kwrsync_exec
if [ "$HOME_SYNC_CRON" = yes ] ; then
	# Home Verzeichnisse syncronisieren
	kwrsync_home_exec no_kwrsync_cron_home_exec
fi
# Verzeichnisse syncronisieren
kwrsync_exec no_kwrsync_cron_exec
exit 0
### Modeline {{{
### vim:ft=zsh:foldmethod=marker
### vim:set ts=4:                                                                               
### }}}
