.\"     Title: KWBACKUP
.\"    Author: Kai Wilke <kiste@netzworkk.de>
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 07/04/2008
.\"    Manual: Benutzerhandbuch f\(:ur kwbackup
.\"    Source: Version 0.1.5
.\"
.TH "KWBACKUP" "1" "07/04/2008" "Version 0.1.5" "Benutzerhandbuch f\(:ur kwbackup"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
kwbackup \- ein Backup Zshell Script.
.SH "SYNTAX"
.HP 9
\fBkwbackup\fR
.SH "BESCHREIBUNG"
.PP
Mit
\fBkwbackup\fR
kann man ein Backup vom System oder von Verzeichnissen ihrer Wahl t\(:atigen\&. Dabei werden alle Daten mit
\fBtar\fR
archiviert und mit
\fBbzip2\fR
komprimiert\&. Muss eine Partition f\(:urs Backup eingebunden werden geschieht das automatisch, falls dies konfiguriert wurde\&.
.SH "OPTIONEN"
.PP
\fBKonfiguration\fR
.RS 4
Konfiguration von
\fBkwbackup\fR\&. Lesen Sie dazu
\fBkwbackuprc\fR(5)\&.
.RE
.PP
\fBBackup\fR
.RS 4
Erstellt ein Backup von Verzeichnissen ihrer Wahl, wenn Sie daf\(:ur die Rechte besitzen\&. Ist f\(:ur Verzeichnisse der Benutzer gedacht\&. Alle 30 Tage wird ein komplettes Backup get\(:atigt, ansonsten fliessen nur ver\(:anderte Dateien, der letzten 7 Tage, ins Backup\&.
.RE
.PP
\fBSystem_Backup\fR
.RS 4
Erstellt ein Backup vom ganzen System ausser von den Home (\fI/home\fR) Verzeichnissen\&. Alle 60 Tage wird ein komplettes Backup get\(:atigt, ansonsten fliessen nur ver\(:anderte Dateien, der letzten 7 Tage, ins Backup\&.
.sp
\fBNotiz:\fR
Dieser Men\(:upunkt wird nur angezeigt, wenn das Script als
\(lqroot\(rq
ausgef\(:uhrt wird\&.
.RE
.SH "DATEI"
.PP
\fI~/\&.kwtools/kwbackuprc\fR
.RS 4
Dies ist die Konfigurations Datei f\(:ur
\fBkwbackup\fR
und
\fBkwbackup_cron\fR\&. F\(:ur weitere Details siehe
\fBkwbackuprc\fR(5)\&.
.RE
.SH "SIEHE AUCH"
.PP
\fBbzip2\fR(1),
\fBkwbackup_cron\fR(1),
\fBkwbackuprc\fR(5),
\fBtar\fR(1)
.SH "AUTOR"
.PP
\fBKai Wilke\fR <\&kiste@netzworkk\&.de\&>
.sp -1n
.IP "" 4
Die Manpage wurde in DocBook XML f\(:ur die Debian Distribution geschrieben\&.
.SH "COPYRIGHT"
Copyright \(co 2002-2008 Kai Wilke
.br
