.\"     Title: KWPWSAFE
.\"    Author: Kai Wilke <kiste@netzworkk.de>
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 01/21/2010
.\"    Manual: Benutzerhandbuch f\(:ur kwpwsafe
.\"    Source: Version 0.0.1
.\"
.TH "KWPWSAFE" "1" "01/21/2010" "Version 0.0.1" "Benutzerhandbuch f\(:ur kwpwsafe"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
kwpwsafe \- ein Zshell Script zur Passwort-Verwaltung.
.SH "SYNTAX"
.HP 9
\fBkwpwsafe\fR
.SH "BESCHREIBUNG"
.PP
Mit
\fBkwpwsafe\fR
k\(:onnen Sie Counterpane "\fIPasswordsafe\fR" Benutzername/Passwort Datenbank bearbeiten\&.
.SH "OPTIONEN"
.PP
\fBKonfiguration\fR
.RS 4
Einstellung der Standard Datenbank, die ge\(:offnet werden soll, und der Passwortl\(:ange, zum generieren eines Passworts\&.
.RE
.PP
\fBDatenbank \(:offnen\fR
.RS 4
Abfrage der Daten, wie Benutzername, Passwort, und Notizen\&. Man kann Eintr\(:age erstellen, \(:andern und l\(:oschen\&.
.RE
.PP
\fBDatenbanken verwalten\fR
.RS 4
Hier k\(:onnen Sie Datenbanken erstellen, deren Passwort \(:andern, importieren, exportieren und nat\(:urlich auch l\(:oschen\&.
.RE
.SH "SIEHE AUCH"
.PP
\fBpwsafe\fR(1)
.sp
.RS 4
.nf
http://nsd\&.dyndns\&.org/pwsafe/
http://passwordsafe\&.sourceforge\&.net/
http://www\&.counterpane\&.com/
.fi
.RE
.sp
.SH "AUTOR"
.PP
\fBKai Wilke\fR <\&kiste@netzworkk\&.de\&>
.sp -1n
.IP "" 4
Die Manpage wurde in DocBook XML f\(:ur die Debian Distribution geschrieben\&.
.SH "COPYRIGHT"
Copyright \(co 2009-2010 Kai Wilke
.br
