.\"     Title: KWRECORD
.\"    Author: Kai Wilke <kiste@netzworkk.de>
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 03/03/2010
.\"    Manual: Benutzerhandbuch f\(:ur kwrecord
.\"    Source: Version 0.1.23
.\"
.TH "KWRECORD" "1" "03/03/2010" "Version 0.1.23" "Benutzerhandbuch f\(:ur kwrecord"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
kwrecord \- Zshell Script zum brennen.
.SH "SYNTAX"
.HP 9
\fBkwrecord\fR
.SH "BESCHREIBUNG"
.PP
\fBkwrecord\fR
dient zum brennen von Dateien und Verzeichnissen, unterschiedlicher Formate\&. Dabei sind die Bereiche in verschiedene Bereiche unterteilt\&. Nachdem brennen werden Sie gefragt, ob die Original Dateien gel\(:oscht werden sollen? Das betrifft in diesen F\(:allen nur die erzeugten
\fIISO\fR
Images oder die fuer
\fBcdrdao\fR
erzeugten
\fITOC\fR\-Dateien\&. In allen F\(:allen wird gepr\(:uft ob eine
\fICD\fR
oder
\fIDVD\fR
im Laufwerk ist und ob es ein Rohling oder schon ein beschriebenes Medium ist\&.
.PP
\fBNotiz:\fR
Bei
\fImp3/ogg\fR
und
\fIPhoto\fR
Dateien d\(:urfen keine Dateiennamen doppelt vorkommen, sonst erstellt
\fBgenisoimage\fR
kein Image\&. Multisession
\fICD/DVDs\fR
werden noch nicht unterst\(:utzt, wie auch einige andere neue Features\&.
.SH "OPTIONEN"
.PP
\fBKonfiguration\fR
.RS 4
Konfiguration der Brennereinstellungen, wie Laufwerke, Treiber, Geschwindigkeit, etc\&.\&.
.RE
.PP
\fBAudio\-CD\fR
.RS 4
Brennt Sound Dateien im Format
\fIwav\fR,
\fImp3\fR
und
\fIogg\fR\&. Wobei die letzten beide reine Daten
\fICDs\fR
werden\&. Aber vielleicht liegen ja auch noch andere Dateien dazwischen oder man m\(:ochte reine
\fIogg\fR
oder
\fImp3 CDs\fR
brennen\&.
.RE
.PP
\fBAUDIO_DVD\fR
.RS 4
Brennt Sound Dateien im Format
\fIwav\fR,
\fImp3\fR
und
\fIogg\fR\&. Wobei die letzten beide reine Daten
\fICDs\fR
werden\&. Aber vielleicht liegen ja auch noch andere Dateien dazwischen oder man m\(:ochte reine
\fIogg\fR
oder
\fImp3 CDs\fR
brennen\&.
.RE
.PP
\fBCD\-kopieren\fR
.RS 4
Kopiert eine
\fICD\fR
1 zu 1 auf einen neuen Rohling\&. Sie ben\(:otigen mindestens 1 Leselaufwerk und 1 CD\-Brenner\&. Diese k\(:onnen auch ein und dasselbe Laufwerk sein\&. Sie werden dann aufgefordert die
\fICD\fR
zu wechseln\&.
.RE
.PP
\fBDVD\-kopieren\fR
.RS 4
Kopiert eine
\fIDVD\fR
1 zu 1 auf einen neuen Rohling\&. Sie ben\(:otigen mindestens 1 Leselaufwerk und 1 DVD\-Brenner\&. Diese k\(:onnen auch ein und dasselbe Laufwerk sein\&. Sie werden dann aufgefordert die
\fIDVD\fR
zu wechseln\&.
.RE
.PP
\fBDaten\-CD\fR
.RS 4
Hier kann man ganze Verzeichnisse oder einzelne Dateien brennen\&. Es werden keine Unterschiede zwischen den Dateien gemacht\&. Es wird alles ausgew\(:ahlte auf
\fICD\fR
gebrannt\&.
.RE
.PP
\fBDaten\-DVD\fR
.RS 4
Hier kann man ganze Verzeichnisse oder einzelne Dateien brennen\&. Es werden keine Unterschiede zwischen den Dateien gemacht\&. Es wird alles ausgew\(:ahlte auf
\fIDVD\fR
gebrannt\&.
.RE
.PP
\fBISO\-CD\fR
.RS 4
Brennt ein oder mehrere
\fIISO\fR
Images auf
\fICD\fR\&.
.RE
.PP
\fBISO\-DVD\fR
.RS 4
Brennt ein oder mehrere
\fIISO\fR
Images auf
\fIDVD\fR\&.
.RE
.PP
\fBPhoto\-CD\fR
.RS 4
Brennt nur Bild Dateien auf
\fICD\fR\&. F\(:ur ganze Verzeichnisse benutzen Sie bitte den Men\(:upunkt
\fBDaten\-CD\fR\&.
.RE
.PP
\fBPhoto\-DVD\fR
.RS 4
Brennt nur Bild Dateien auf
\fIDVD\fR\&. F\(:ur ganze Verzeichnisse benutzen Sie bitte den Men\(:upunkt
\fBDaten\-DVD\fR\&.
.RE
.PP
\fBVideo\-CD\fR
.RS 4
Brennt Video\-CDs\&.
.RE
.PP
\fBVideo_DVD\fR
.RS 4
Brennt Video\-DVDs\&.
.RE
.PP
\fBCD\-l\(:oschen\fR
.RS 4
L\(:oschen von
\fICD+\-RWs\fR\&. Entweder minimal oder vollst\(:andig\&.
.RE
.PP
\fBDVD\-formatieren\fR
.RS 4
Formatieren von
\fIDVD+\-RWs\fR
und
\fIDVD\-Rams\fR\&.
.RE
.SH "DATEI"
.PP
\fI~/\&.kwtools/cd_dvdrc\fR
.RS 4
Dies ist die Konfigurations Datei f\(:ur alle kwtools Scripts die brennen k\(:onnen\&. F\(:ur weitere Details siehe
\fBcd_dvdrc\fR(5)\&.
.RE
.SH "SIEHE AUCH"
.PP
\fBcd_dvdrc\fR(5),
\fBcdrdao\fR(1),
\fBgenisoimage\fR(1),
\fBgrowisofs\fR(1)
.SH "AUTOR"
.PP
\fBKai Wilke\fR <\&kiste@netzworkk\&.de\&>
.sp -1n
.IP "" 4
Die Manpage wurde in DocBook XML f\(:ur die Debian Distribution geschrieben\&.
.SH "COPYRIGHT"
Copyright \(co 2002-2010 Kai Wilke
.br
