.\"     Title: KWRAID
.\"    Author: Kai Wilke <kiste@netzworkk.de>
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 01/27/2010
.\"    Manual: Benutzerhandbuch f\(:ur kwraid
.\"    Source: Version 0.3.3
.\"
.TH "KWRAID" "8" "01/27/2010" "Version 0.3.3" "Benutzerhandbuch f\(:ur kwraid"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
kwraid \- ein Zshell Script f\(:ur die Administration von RAID Arrays
.SH "SYNTAX"
.HP 7
\fBkwraid\fR
.SH "BESCHREIBUNG"
.PP
Mit dem Script
\fBkwraid\fR
k\(:onnen Sie RAID Arrays erstellen, Partitionen/Festplatten tauschen, einen Monitor einstellen, Statistiken anzeigen lassen und nat\(:urlich auch die Konfigurationsdatei von
\fBmdadm\fR
berabeiten\&. Lesen sie vorher das Software\-RAID\-HOWTO\&.
.sp
.RS 4
.nf
http://www\&.linuxhaven\&.de/dlhp/HOWTO/DE\-Software\-RAID\-HOWTO\&.html
.fi
.RE
.SH "OPTIONEN"
.PP
\fBKonfiguration\fR
.RS 4
Hier kann man die Konfiguration f\(:ur
\fBmdadm\fR
bearbeiten\&. Dazu geh\(:oren die Einstellung von Standardwerten f\(:ur die Erstellung von Arrays oder Mailadressen,\&.\&.\&.\&.
.RE
.PP
\fBLaufwerke\fR
.RS 4
Hier kann man RAID Arrays erstellen, \(:andern, vergr\(:ossern, reparieren, Partitionen/Festplatten wechseln und Arrays l\(:oschen\&.
.RE
.PP
\fBMonitor\fR
.RS 4
Hier kann man einen RAID Monitor einstellen, wobei man per mail benachrichtigt wird, wenn in einem RAID Array Partitionen/Festplatten ausgefallen/besch\(:adigt sind\&.
.sp
\fBDebian:\fR
Zur Einstellung vom RAID Monitor wird
\(lq\fBdpkg\-reconfigure mdadm\fR\(rq
verwendet\&.
.sp
\fBSuSE:\fR
Zur Einstellung vom RAID Monitor wird
\fByast2\fR
verwendet (\fByast2\fR
\fBsysconfig \-> System \-> File systems \-> Mdadm\fR)\&.
.sp
\fBCentOS|Fedora:\fR
Hier ist noch nichts\&.
.RE
.PP
\fBStatus\fR
.RS 4
Statusanzeige der RAID Arrays\&.
.RE
.SH "DATEI"
.PP
\fI/etc/mdadm/mdadm\&.conf\fR
.RS 4
Konfigurations Datei f\(:ur
\fBmdadm\fR
(\fBDebian\fR)\&. Siehe
\fBmdadm.conf\fR(5)
f\(:ur weitere Details\&.
.RE
.PP
\fI/etc/mdadm\&.conf\fR
.RS 4
Konfigurations Datei f\(:ur
\fBmdadm\fR
(\fB(Open)SuSE, Fedora und CentOS\fR)\&. Siehe
\fBmdadm.conf\fR(5)
f\(:ur weitere Details\&.
.RE
.SH "SIEHE AUCH"
.PP
\fBmd\fR(8),
\fBmdadm.conf\fR(5),
\fBmdadm\fR(8),
\fBmdadm-startall\fR(8),
\fBmdrun\fR(8)
.SH "AUTOR"
.PP
\fBKai Wilke\fR <\&kiste@netzworkk\&.de\&>
.sp -1n
.IP "" 4
Die Manpage wurde in DocBook XML f\(:ur die Debian Distribution geschrieben\&.
.SH "COPYRIGHT"
Copyright \(co 2002-2010 Kai Wilke
.br
