.\"     Title: KWRSYNC_BACKUP_CRON
.\"    Author: Kai Wilke <kiste@netzworkk.de>
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 06/12/2008
.\"    Manual: Benutzerhandbuch f\(:ur kwrsync_backup_cron
.\"    Source: Version 0.0.6
.\"
.TH "KWRSYNC_BACKUP_CRON" "8" "06/12/2008" "Version 0.0.6" "Benutzerhandbuch f\(:ur kwrsync_b"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
kwrsync_backup_cron \- Crontab Script f\(:ur das Script kwrsync_backup.
.SH "SYNTAX"
.HP 20
\fBkwrsync_backup_cron\fR
.SH "BESCHREIBUNG"
.PP
\fBkwrsync_backup_cron\fR
liest die Datei
\fI/etc/kwtools/kwrsync_backup\&.cf\fR
und
\fI/etc/kwtools/kwrsync_backup\-excludes\fR
ein und wird vom
\fBCron\fR
Daemon ausgef\(:uhrt\&. Bei Beendigung wird eine Mail an root verschickt\&.
.SH "DATEIEN"
.PP
\fI/etc/kwtools/kwrsync_backup\&.cf\fR
.RS 4
Haupt Konfiguration Datei f\(:ur
\fBkwrsync_backup_cron\fR\&. Siehe
\fBkwrsync_backup.cf\fR(5)
f\(:ur weitere Details\&.
.RE
.PP
\fI/etc/kwtools/kwrsync_backup\-excludes\fR
.RS 4
Beinhaltet Verzeichnisse/Dateien die nicht mit einbezogen werden sollen (z\&.B\&.
\fI/sys\fR,
\fI/proc\fR)
.RE
.SH "SIEHE AUCH"
.PP
\fBcron\fR(8),
\fBcrontab\fR(1),
\fBcrontab\fR(5),
\fBkwrsync_backup\fR(8),
\fBkwrsync_backup.cf\fR(5),
\fBrsync\fR(1)
.SH "AUTOR"
.PP
\fBKai Wilke\fR <\&kiste@netzworkk\&.de\&>
.sp -1n
.IP "" 4
Die Manpage wurde in DocBook XML f\(:ur die Debian Distribution geschrieben\&.
.SH "COPYRIGHT"
Copyright \(co 2002-2008 Kai Wilke
.br
